permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 夏顺新
  email: xxiiaass@sina.com
  link: http://kevinxia.org
  weibo: http://weibo.com/xxiiaass
  github: http://github.com/KevinXiasx

# 站点信息
title: Kevin学习记录 
description: 学习记录
url: http://kevinxia.org
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: kevinxia.org

# disqus 设置
disqus:
  shortname: suyan-zh
