permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 夏顺新
  email: xxiiaass@sina.com
  weibo: http://weibo.com/xxiiaass
  github: http://github.com/KevinXiasx

# 站点信息
title: Kevin学习记录 
description: 学习记录
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://imgsrc.baidu.com/forum/w%3D580/sign=b0847c3fd00735fa91f04eb1ae500f9f/3eb69e39b6003af3211b0244312ac65c1138b6d2.jpg
favicon: http://www.jianbihua.cc/uploads/allimg/140216/2-1402161Q401S6.jpg

# google analytics 设置
ga:
  id: UA-54767140-1

# disqus 设置
disqus:
  shortname: kevin-zh
